# deployment-nodejs.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-app
  template:
    metadata:
      labels:
        app: task-manager-app
    spec:
      containers:
        - name: task-manager-app
          image: task-manager-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: PROD_DB_HOST
              value: task-manager-db-service
            - name: PROD_DB_NAME
              value: task_manager_db
            - name: PROD_DB_USER
              value: postgres
            - name: PROD_DB_PASSWORD
              value: test@123
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-app-service
spec:
  selector:
    app: task-manager-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer
