# deployment-postgres.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-db
  template:
    metadata:
      labels:
        app: task-manager-db
    spec:
      containers:
        - name: task-manager-db
          image: task-manager-db:latest
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-db-service
spec:
  selector:
    app: task-manager-db
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
