version: '3'

services:
  task-management-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  task-management-app:
    image: node:18
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: PROD
      PROD_DB_HOST: task-management-db
      PROD_DB_NAME: ${DB_NAME}
      PROD_DB_USER: ${DB_USER}
      PROD_DB_PASSWORD: ${DB_PASSWORD}
      PROD_DB_PORT: 5432
      JWT_KEY: ${JWT_KEY}
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run migrate && npm start"
    depends_on:
      - task-management-db
    networks:
      - mynetwork

volumes:
  pg-data:

networks:
  mynetwork:
    driver: bridge
