version: '3'

services:
  task-management-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pacis123
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  task-management-app:
    image: node:18
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: PROD
      PROD_DB_HOST: task-management-db
      PROD_DB_PORT: 5432
      PROD_DB_USER: postgres
      PROD_DB_NAME: task_management_db
      PROD_DB_PASSWORD: pacis123
      JWT_KEY: $JWT_KEY
      DB_DIALECT: postgresql
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run migrate && npm start"
    depends_on:
      - task-management-db
    networks:
      - mynetwork

volumes:
  pg-data:

networks:
  mynetwork:
    driver: bridge
